export default [
  {
    description: "Cartão de Crédito",
    amount: "600.90",
    type: "saída",
    frequency: "recorrente",
    date: "2019-01-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-01-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-01-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-01-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-01-15",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-01-21",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-01-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "600.90",
    type: "saída",
    frequency: "recorrente",
    date: "2019-02-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-02-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-02-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-02-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-02-15",
  },
  {
    description: "Lanche",
    amount: "80.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-02-21",
  },
  {
    description: "Lanche",
    amount: "80.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-02-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "800.90",
    type: "saída",
    frequency: "recorrente",
    date: "2019-03-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-03-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-03-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-03-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-03-15",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-03-21",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-03-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "300.90",
    type: "saída",
    frequency: "recorrente",
    date: "2019-04-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-04-11",
  },
  {
    description: "Internet",
    amount: "150.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-04-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-04-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-04-15",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-04-21",
  },
  {
    description: "Lanche",
    amount: "100.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-04-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "1200.90",
    type: "saída",
    frequency: "recorrente",
    date: "2019-05-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-05-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-05-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-05-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-05-15",
  },
  {
    description: "Lanche",
    amount: "300.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-05-21",
  },
  {
    description: "Lanche",
    amount: "120.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-05-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "600.90",
    type: "saída",
    frequency: "recorrente",
    date: "2019-06-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-06-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-06-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-06-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-06-15",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-06-21",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-06-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "600.90",
    type: "saída",
    frequency: "recorrente",
    date: "2019-07-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-07-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-07-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-07-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-07-15",
  },
  {
    description: "Lanche",
    amount: "80.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-07-21",
  },
  {
    description: "Lanche",
    amount: "80.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-07-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "800.90",
    type: "saída",
    frequency: "recorrente",
    date: "2019-08-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-08-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-08-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-08-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-08-15",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-08-21",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-08-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "300.90",
    type: "saída",
    frequency: "recorrente",
    date: "2019-09-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-09-11",
  },
  {
    description: "Internet",
    amount: "150.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-09-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-09-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-09-15",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-09-21",
  },
  {
    description: "Lanche",
    amount: "100.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-09-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "1800.90",
    type: "saída",
    frequency: "recorrente",
    date: "2019-10-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-10-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-10-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-10-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-10-15",
  },
  {
    description: "Lanche",
    amount: "500.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-10-21",
  },
  {
    description: "Lanche",
    amount: "400.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-10-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "1800.90",
    type: "saída",
    frequency: "recorrente",
    date: "2019-11-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-11-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-11-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-11-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-11-15",
  },
  {
    description: "Lanche",
    amount: "500.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-11-21",
  },
  {
    description: "Lanche",
    amount: "400.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-11-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "3000.90",
    type: "saída",
    frequency: "recorrente",
    date: "2019-12-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-12-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-12-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-12-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2019-12-15",
  },
  {
    description: "Lanche",
    amount: "500.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-12-21",
  },
  {
    description: "Lanche",
    amount: "400.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-12-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "600.90",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-01-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-01-15",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-01-21",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-01-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "600.90",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-02-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-02-15",
  },
  {
    description: "Lanche",
    amount: "80.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-02-21",
  },
  {
    description: "Lanche",
    amount: "80.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-02-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "800.90",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-03-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-03-15",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-03-21",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-03-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "300.90",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-04-11",
  },
  {
    description: "Internet",
    amount: "150.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-04-15",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-04-21",
  },
  {
    description: "Lanche",
    amount: "100.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-04-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "1200.90",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-05-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-05-15",
  },
  {
    description: "Lanche",
    amount: "300.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-05-21",
  },
  {
    description: "Lanche",
    amount: "120.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-05-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "600.90",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-06-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-06-15",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-06-21",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-06-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "600.90",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-07-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-07-15",
  },
  {
    description: "Lanche",
    amount: "80.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-07-21",
  },
  {
    description: "Lanche",
    amount: "80.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-07-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "800.90",
    type: "saída",
    frequency: "recorrente",
    date: "2020-08-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-08-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-08-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-08-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-08-15",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-08-21",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-08-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "300.90",
    type: "saída",
    frequency: "recorrente",
    date: "2020-09-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-09-11",
  },
  {
    description: "Internet",
    amount: "150.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-09-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-09-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-09-15",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-09-21",
  },
  {
    description: "Lanche",
    amount: "100.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-09-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "1800.90",
    type: "saída",
    frequency: "recorrente",
    date: "2020-10-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-10-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-10-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-10-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-10-15",
  },
  {
    description: "Lanche",
    amount: "500.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-10-21",
  },
  {
    description: "Lanche",
    amount: "400.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-10-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "1800.90",
    type: "saída",
    frequency: "recorrente",
    date: "2020-11-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-11-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-11-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-11-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-11-15",
  },
  {
    description: "Lanche",
    amount: "500.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-11-21",
  },
  {
    description: "Lanche",
    amount: "400.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-11-29",
  },

  {
    description: "Cartão de Crédito",
    amount: "3000.90",
    type: "saída",
    frequency: "recorrente",
    date: "2020-12-10",
  },
  {
    description: "Lanche",
    amount: "30.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-12-11",
  },
  {
    description: "Internet",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-12-08",
  },
  {
    description: "Parcela Xbox",
    amount: "130.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-12-12",
  },
  {
    description: "Carro",
    amount: "650.00",
    type: "saída",
    frequency: "recorrente",
    date: "2020-12-15",
  },
  {
    description: "Lanche",
    amount: "500.90",
    type: "saída",
    frequency: "eventual",
    date: "2020-12-21",
  },
  {
    description: "Lanche",
    amount: "400.90",
    type: "saída",
    frequency: "eventual",
    date: "2019-12-29",
  },
];
